name: Clasificación facial por imagen

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'URL de la imagen a clasificar'
        required: true
      threshold:
        description: 'Umbral de similitud (0.0-1.0)'
        required: false
        default: '0.75'

jobs:
  classify:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0

    - name: Instalar paquetes de Python
      run: |
        pip install --upgrade pip
        pip install opencv-python numpy psycopg2-binary python-dotenv ultralytics keras-facenet scikit-learn

    - name: Descargar el modelo de YOLO
      run: |
        mkdir -p models
        python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"

    - name: Clasifiación
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/classify_face.py \
          --image_url "${{ inputs.image_url }}" \
          --threshold "${{ inputs.threshold }}"
