name: Clasificación facial por imagenes

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'URL pública de la imagen'
        required: true

jobs:
  classify:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar las dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0

    - name: Instalar paquetes de Python
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install \
          tensorflow-cpu==2.12.0 \
          opencv-python-headless \
          ultralytics \
          psycopg2-binary \
          python-dotenv \
          scikit-learn \
          keras-facenet

    - name: Verificar la instalación
      run: |
        python -c "import tensorflow, cv2, psycopg2, dotenv; print('Dependencias verificadas')"

    - name: Descargar el modelo de YOLO
      run: |
        mkdir -p models
        python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"

    - name: Proceso de clasifiación
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/Clasificacion_rostro.py --image_url "${{ inputs.image_url }}"
