name: Clasifiación facial por imagen

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'URL de la imagen a clasificar'
        required: true

jobs:
  classify:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow-cpu==2.12.0  # Versión ligera de TensorFlow
        pip install keras-facenet opencv-python ultralytics psycopg2-binary scikit-learn

    - name: Download YOLO model
      run: |
        mkdir -p models
        python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"

    - name: Run classification
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/classify_face.py --image_url "${{ inputs.image_url }}"
