name: Facial Embeddings Registration

on:
  workflow_dispatch:
    inputs:
      full_name:
        description: 'Nombre completo (ej. Juan Pérez López)'
        required: true
        default: 'Usuario Prueba'
      folder_name:
        description: 'Nombre de la carpeta en dataset/ (ej. usuario1)'
        required: true
        default: 'persona1'

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0
        pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install tensorflow-cpu==2.12.0 opencv-python-headless

    - name: Verify dataset folder
      run: |
        if [ ! -d "dataset/${{ inputs.folder_name }}" ]; then
          echo "::error::Carpeta dataset/${{ inputs.folder_name }} no encontrada"
          echo "Las carpetas disponibles son:"
          ls dataset/ || echo "No hay carpetas en dataset/"
          exit 1
        fi
        echo "✔ Carpeta dataset/${{ inputs.folder_name }} verificada"

    - name: Run registration
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/register_user.py \
          --full_name "${{ inputs.full_name }}" \
          --folder_name "${{ inputs.folder_name }}"
