name: Facial Embeddings Registration

on:
  workflow_dispatch:
    inputs:
      person_name:
        description: 'Nombre completo (incluye apellidos)'
        required: true
        default: 'Nombre Apellido'

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install tensorflow-cpu==2.12.0 opencv-python-headless

    - name: Download YOLO model
      run: |
        mkdir -p models
        python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"

    - name: Verify dataset
      run: |
        PERSON_NAME="${{ inputs.person_name }}"
        FOLDER_NAME="${PERSON_NAME%% *}"  # Extrae primer nombre para carpeta
        
        if [ ! -d "dataset/$FOLDER_NAME" ]; then
          echo "::error::No existe dataset/$FOLDER_NAME"
          exit 1
        fi

    - name: Run registration
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/register_user.py \
          --full_name "${{ inputs.person_name }}" \
          --min_confidence 0.7 \
          --max_images 30
