name: Register User Embeddings

on:
  workflow_dispatch:
    inputs:
      person_name:
        description: 'Nombre de la persona'
        required: true
        default: 'persona1'

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache models
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ultralytics
          ~/.keras
        key: ${{ runner.os }}-models-${{ hashFiles('scripts/requirements.txt') }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Download YOLO model
      run: |
        mkdir -p models
        # Using official Ultralytics YOLOv8 face detection model
        python -c "
        from ultralytics import YOLO
        model = YOLO('yolov8n.pt')  # Downloads standard YOLOv8n
        model.export(format='onnx')  # Optional: export to ONNX if needed
        "
        # Alternative direct download if needed:
        # wget -O models/yolov8n-face.pt https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt
        
    - name: Run registration
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/register_user.py --person_name ${{ inputs.person_name }}
