name: Facial Embeddings Registration

on:
  workflow_dispatch:
    inputs:
      person_name:
        description: 'Nombre de la persona (debe coincidir con el nombre de la carpeta en dataset/)'
        required: true
        default: 'persona1'

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    # Paso 1: Obtener el código
    - uses: actions/checkout@v4

    # Paso 2: Configurar Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Paso 3: Dependencias del sistema
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx

    # Paso 4: Cache
    - name: Cache models
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ultralytics
          ~/.keras
          ./models
        key: ${{ runner.os }}-models-${{ hashFiles('scripts/requirements.txt') }}

    # Paso 5: Instalar dependencias Python
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install tensorflow-cpu==2.12.0

    # Paso 6: Descargar modelo YOLO
    - name: Download YOLO model
      run: |
        mkdir -p models
        python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"

    # Paso 7: Verificar dataset
    - name: Verify dataset
      run: |
        if [ ! -d "dataset/${{ inputs.person_name }}" ]; then
          echo "::error::No existe dataset/${{ inputs.person_name }}"
          exit 1
        fi

    # Paso 8: Ejecutar registro
    - name: Run registration
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/register_user.py --person_name "${{ inputs.person_name }}"
