name: Register User Embeddings

on:
  workflow_dispatch:
    inputs:
      person_name:
        description: 'Nombre de la persona (debe coincidir con la carpeta en dataset/)'
        required: true
        default: 'persona1'

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache models
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ultralytics
          ~/.keras
          ./models
        key: ${{ runner.os }}-models-${{ hashFiles('scripts/requirements.txt') }}
    
    - name: Verify dataset
      run: |
        if [ ! -d "dataset/${{ inputs.person_name }}" ]; then
          echo "::error::No existe la carpeta dataset/${{ inputs.person_name }}"
          exit 1
        fi
        echo "✔ Carpeta de dataset verificada"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Download YOLO model
      run: |
        mkdir -p models
        wget -O models/yolov8n-face-lindevs.pt \
          https://github.com/lindevs/yolov8-face/releases/download/v0.0.1/yolov8n-face.pt
        
        # Verificar integridad del modelo
        filesize=$(wc -c <"models/yolov8n-face-lindevs.pt")
        if [ "$filesize" -lt 10000000 ]; then
          echo "::error::El modelo descargado es demasiado pequeño (posible error)"
          exit 1
        fi
    
    - name: Run registration
      env:
        NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      run: |
        python scripts/register_user.py \
          --person_name "${{ inputs.person_name }}"
