name: Test Neon Connection
on: [push]

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install psycopg2-binary python-dotenv
      - run: python test_neon.py
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}